# CLI Engineer Configuration File
# 
# API keys are stored in environment variables:
# - OPENROUTER_API_KEY for OpenRouter
# - OPENAI_API_KEY for OpenAI  
# - ANTHROPIC_API_KEY for Anthropic

[ai_providers.openai]
enabled = true
model = "gpt-4.1"
temperature = 1
cost_per_1m_input_tokens = 2.000
cost_per_1m_output_tokens = 8.000
max_context_tokens = 1047576

[ai_providers.anthropic]
enabled = false
model = "claude-sonnet-4-0"
temperature = 1
cost_per_1m_input_tokens = 3.00
cost_per_1m_output_tokens = 15.00
max_context_tokens = 200000

[ai_providers.openrouter]
enabled = false
model = "deepseek/deepseek-r1-0528-qwen3-8b"
temperature = 0.2
cost_per_1m_input_tokens = 0.06
cost_per_1m_output_tokens = 0.09
max_context_tokens = 65536

[execution]
# Maximum iterations for the agentic loop
max_iterations = 2

# Enable parallel task execution
parallel_enabled = true

# Artifact directory
artifact_dir = "./artifacts"

# Isolated execution environment
isolated_execution = false

# Cleanup artifacts on exit
cleanup_on_exit = false

# Disable automatic git repository initialization unless explicitly requested
disable_auto_git = true

[ui]
# Enable colorful terminal output
colorful = true

# Show progress bars
progress_bars = true

# Show real-time metrics
metrics = true

# Output format: "terminal", "json", or "plain"
output_format = "terminal"

[context]
# Fallback maximum tokens (actual model context size is used when available)
max_tokens = 65536

# Compression threshold (0.0 to 1.0)
compression_threshold = 0.4

# Enable context caching
cache_enabled = true
